[package]
name = "fsai-starter"
version = "0.1.0"
authors = ["shaman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resource-unit = { path = "../resource-unit" }
