[package]
name = "fsai-starter"
version = "0.1.1"
authors = ["shaman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resource-manager = { path = "../resource-manager" }
# ncurses-rs = "0.0.3"
ncurses = "5.100.0"
